### ISSUE TITLE
No access token was found.

### ISSUE THREAD

**Issue by vvs100x** [easton36/clashgg-sniper#1]
0|Clash.gg Bot  | 2023-09-21 21:29 +02:00: 2023-09-21 21:29:12 +02:00: [ERROR] [CHROME] An error occurred while fetching the Cloudflare clearance cookie: Waiting for selector `#__next` failed: Waiting failed: 60000ms exceeded
0|Clash.gg Bot  | 2023-09-21 21:29 +02:00: 2023-09-21 21:29:13 +02:00: [ERROR] [API] An error occurred while getting the access token: Request failed with status code 403
0|Clash.gg Bot  | 2023-09-21 21:29 +02:00: 2023-09-21 21:29:13 +02:00: [ERROR] No access token was found. This could be an issue with your refresh token cookie, or more likely, your cf_clearance cookie. cf_clearance expires often.

getting this error when refresh and clearance token are set.

**Comment by samplics** [comment]
Please see if this fixes your issue
