### ISSUE TITLE
read eCONNRESET

### ISSUE THREAD

**Issue by alirizafrat** [easton36/clashgg-sniper#4]
https://cdn.discordapp.com/attachments/999422589992718379/1164750759938768947/image.png?ex=654459ad&is=6531e4ad&hm=4f005c458e1ce027614dc79ab0de7287fa9e2d55227575fa60feeb547cc35639&
 im getting this error im tried something but im failed can u help ?

**Comment by samplics** [comment]
Using puppeteer to fetch CF_CLEARANCE doesn’t work, you need to set it manually

**Comment by alirizafrat** [comment]
How exactly can I do it? Do I need to add it to the code or somewhere else?

**Comment by samplics** [comment]
Read the setup instructions
