### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Raemnn** [easton36/clashgg-sniper#5]
This programs not working. I've try the all solution. I'm getting the same error as @alirizafrat.

**Comment by samplics** [comment]
If you fill in all details into the .env file it does work. I am currently running the program as we speak

**Comment by Raemnn** [comment]
I fulfilled everything on the to-do list to the letter. I tried to reach you on telegram regarding the problem. I would be very happy if you could help me. It keeps saying " [ERROR] [CHROME] An error occurred while fetching the Cloudflare clearance cookie: Waiting for selector '#__next' failed: Waiting Failed: 60000ms exceeded
[API] An error occurred while getting thr access toke: read ECONNRESET
[ERROR] No access token was found. This could be an issue with your refresh token cookie, or more likely your cf_clearance cookie. cf_clearance expires often.

**Comment by samplics** [comment]
The headless chrome feature doesn’t work anymore which is why I’ve removed it from the main script. If you have features to add, make a pull request.
